Make Eclipse stop giving warnings
LibreOffice/loeclipse pull request #126
Opened 2024-12-30 17:22 UTC by prrvchr

- In order to take advantage of the warnings in Eclipse the **CheckStyle** plugin has been restarted (ie: it was no longer correctly configured) and all files whose code did not meet the requirements of the `/build/checkstyle.xml` file have been updated. It is expected that the file headers (license and copyright) will be modified in order to avoid the last warnings still visible in Eclipse.
- Java 17 is now the minimum version. This seem to be required by the various eclipse archives that LOEclipse uses.
- The template java file `java/source/org/libreoffice/ide/eclipse/java/registration/RegistrationHandler.java.tpl` has been rewritten using generics so that Eclipse warnings stop.
- The test file `core/source/org/libreoffice/ide/eclipse/core/wizards/pages/ManifestExportPageControllerTest.java` has been moved to the `core/source/org/libreoffice/ide/eclipse/core/unittests` folder to allow error-free compilation. See issue#125.

2025-01-06 11:44 UTC, smehrbrodt requested changes
Looks good!
There are a few places where a `p` prefix has been added to variable names (I commented two, but there are more). What was the motivation for that?

2025-01-06 11:44 UTC, smehrbrodt commented on build.properties
> +java_target = 17
Is it necessary to raise the target version to 17 too?

I'm fine with raising the source level, but would raise the target level only as far as it's really required.

2025-01-06 11:44 UTC, smehrbrodt commented on python/source/org/libreoffice/ide/eclipse/python/utils/TemplatesHelper.java
> +        Class<?> pClazz, String pDestPath, boolean pSameFileName, Object... pArgs) {
why the `p` prefix here?

2025-01-06 11:44 UTC, smehrbrodt commented on python/source/org/libreoffice/ide/eclipse/python/PythonBuilder.java
> +    private void getPythonFiles(IFolder pSourceFolder, ArrayList<IFile> pPythonFiles, IUnoidlProject pUnoPrj) {
Why the `p` prefix here?

2025-01-06 12:01 UTC, prrvchr commented
> Looks good! There are a few places where a `p` prefix has been added to variable names (I commented two, but there are more). What was the motivation for that?

Thank for reviewing.

I followed what was initially done with the `/build/checkstyle.xml` file. 
```
    <module name="ParameterName">
      <property name="format" value="^p[A-Z][a-zA-Z0-9]*$"/>
    </module>

```
It seems that all methods must have parameters starting with `p`, I think like method `p`arameter? Maybe I added this in places that didn't require it? I'll remove it if I see any such cases.

2025-01-06 12:07 UTC, smehrbrodt commented
> It seems that all methods must have parameters starting with p, I think like method parameter? Maybe I added this in places that didn't require it? I'll remove it if I see any such cases.

Ok then I would rather update the `checkstyle.xml` file. Adding this prefixes is a bit weird for java code I think.

2025-01-06 12:07 UTC, prrvchr commented on build.properties
> +java_target = 17
I admit that this is a bit beyond me, I am not sufficiently understanding about the compilation of Java modules.
What is certain is that compilation remains possible with 1.8 as it was.

2025-01-06 12:09 UTC, prrvchr commented on python/source/org/libreoffice/ide/eclipse/python/utils/TemplatesHelper.java
> +        Class<?> pClazz, String pDestPath, boolean pSameFileName, Object... pArgs) {
If we keep this rule, then the parameters of the methods start with `p`.

2025-01-06 12:09 UTC, prrvchr commented on python/source/org/libreoffice/ide/eclipse/python/PythonBuilder.java
> +    private void getPythonFiles(IFolder pSourceFolder, ArrayList<IFile> pPythonFiles, IUnoidlProject pUnoPrj) {
If we keep this rule, then the parameters of the methods start with `p`.

2025-01-06 12:28 UTC, prrvchr commented
Ok no problem, I can remove this rule and modify the files accordingly?

2025-01-06 12:32 UTC, smehrbrodt commented
> Ok no problem, I can remove this rule and modify the files accordingly?

Yes please.

2025-01-13 06:50 UTC, smehrbrodt approved these changes

2025-01-13 06:50 UTC, merged