Bug fixes
LibreOffice/loeclipse pull request #48
Opened 2017-02-28 15:56 UTC by Mianto

RegistrationHandler.class shows an error message when it is empty

2017-02-28 16:01 UTC, smehrbrodt requested changes
Looks good in general, just note the comments I left inline.

2017-02-28 16:01 UTC, smehrbrodt commented on java/source/org/libreoffice/ide/eclipse/java/JavaResourceDeltaVisitor.java
> +                PluginLogger.error(ResourceHelper.Messages.getString("RegistrationHelper.WriteClassesListError"));
The error message talks about a write error, but this is a read error I guess?

2017-02-28 16:01 UTC, smehrbrodt commented on java/source/org/libreoffice/ide/eclipse/java/JavaResourceDeltaVisitor.java
> +                PluginLogger.error(ResourceHelper.Messages.getString("RegistrationHelper.WriteClassesListError"));
Same here.

2017-02-28 16:01 UTC, smehrbrodt commented on core/doc/help/html/userdoc/javatuto/index.html
> +Eclipse using the <a href=https://marketplace.eclipse.org/content/loeclipse>Eclipse Marketplace</a>.<br/><br/>
Please move this doc change in a separate pull request.

2017-02-28 16:02 UTC, smehrbrodt commented
Also please add a more descriptive PR title, like "Show error message when RegistrationHandler.classes is empty"

2017-02-28 17:17 UTC, Mianto commented
Please review the changes now.

2017-02-28 18:33 UTC, smehrbrodt commented
Did you test this?

2017-03-01 04:41 UTC, Mianto commented
Sorry I have not tested it. I will test it and commit changes.Sorry once again.

2017-03-01 17:56 UTC, Mianto commented
Review my changes now.

2017-03-10 09:21 UTC, smehrbrodt commented
How did you test this? Were you able to launch an Eclipse instance with the LOEclipse plugin and verify that your fix works, as described in the [readme](https://github.com/LibreOffice/loeclipse#development)?

2018-05-16 09:31 UTC, smehrbrodt commented
Superseded by #67.

2018-05-16 09:31 UTC, closed without merging