Java8+updateproj
LibreOffice/loeclipse pull request #73
Opened 2019-06-28 18:04 UTC by michaelmassee

Hi,
update to Java 8  and 2 new Eclipse Projects for building a Feature and Update.
that is the way i do so with my Eclipse Plugins in the Company. 

when merge ?? , then  please check if all the ids and names are correct.

2019-07-01 09:03 UTC, smehrbrodt requested changes
Thanks a lot! Just please no version update in this patch.

2019-07-01 09:03 UTC, smehrbrodt commented on core/META-INF/MANIFEST.MF
> +Bundle-Version: 3.0.1
Please no version change in this patch. Version will be updated when a release is done.

2019-07-01 09:03 UTC, smehrbrodt commented on java.feature/feature.xml
> +   <description url="http://www.example.com/description">
where is this domain shown?

2019-07-08 10:16 UTC, smehrbrodt commented
Any update here?
If you need help let me know.

2019-07-10 20:46 UTC, michaelmassee commented
just cleanup the junit test, before i do some more bugfixes

2019-12-23 09:46 UTC, closed without merging